### PR TITLE
Function clarification

### PR DESCRIPTION
**Pull request by Asegeas**
Initial commit edited the functions in luumba to encourage reading of the README as well as providing a link to the readme on github

### CODE REVIEW

**Comment by Asegeas** [comment]
I am not ready to commit this branch

**Comment by Asegeas** [comment]
https://gemini-home-entertainment.fandom.com/wiki/Nature%27s_Mockery

**Comment by Asegeas** [comment]
> https://gemini-home-entertainment.fandom.com/wiki/Nature%27s_Mockery

I included this as a new plant feel free to tell me to remove this.

**Comment by Asegeas** [comment]
I am comfortable merging if you think this is acceptable
Treehouse renders are not completed yet...

@dluman

**Review by dluman — APPROVED** [review]
Interested in getting renders put together, but these changes can be merged as incremental improvements.

**Pull request merged**
